Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HandleFormSubmit:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
      CodeUri: ./
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:sendEmail
                - ses:sendRawEmail
              Resource: '*'
      Events:
        FormsApi:
          Type: Api
          Properties:
            Path: /contactme
            Method: POST

